"""empty message

Revision ID: 1006ff443614
Revises: e10381df5ef1
Create Date: 2019-03-23 23:22:20.985892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1006ff443614'
down_revision = 'e10381df5ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'user_agent')
    # ### end Alembic commands ###
