"""empty message

Revision ID: a992baf1e3ec
Revises: b26b8edbe29a
Create Date: 2019-02-21 22:19:24.501464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a992baf1e3ec'
down_revision = 'b26b8edbe29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dom_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agentId', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dom_commands_agentId'), 'dom_commands', ['agentId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dom_commands_agentId'), table_name='dom_commands')
    op.drop_table('dom_commands')
    # ### end Alembic commands ###
