"""empty message

Revision ID: b26b8edbe29a
Revises: 
Create Date: 2018-11-28 21:01:53.633579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26b8edbe29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=156), nullable=False),
    sa.Column('first_seen', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_seen', sa.TIMESTAMP(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('port', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agentId', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('lastUpdated', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_agentId'), 'modules', ['agentId'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('authKey', sa.Text(), nullable=False),
    sa.Column('authSecret', sa.Text(), nullable=False),
    sa.Column('agentId', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agentId'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_agentId'), 'registrations', ['agentId'], unique=False)
    op.create_table('urls',
    sa.Column('id', sa.String(length=156), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('agentId', sa.Text(), nullable=False),
    sa.Column('time_stamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['agentId'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_agentId'), 'urls', ['agentId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_agentId'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_registrations_agentId'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_modules_agentId'), table_name='modules')
    op.drop_table('modules')
    op.drop_table('agents')
    # ### end Alembic commands ###
