"""empty message

Revision ID: e10381df5ef1
Revises: a992baf1e3ec
Create Date: 2019-02-24 03:14:13.754381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10381df5ef1'
down_revision = 'a992baf1e3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('authKey', sa.Text(), nullable=False),
    sa.Column('authSecret', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_registrations')
    # ### end Alembic commands ###
